#!/usr/bin/env python3
"""
This script creates the directory structure for the automated museum project
with MQTT control system - creates only folders and blank files with comments.
"""

import os
import json
import configparser

def create_directory(path):
    """Create directory if it doesn't exist."""
    if not os.path.exists(path):
        os.makedirs(path)
        print(f"Created directory: {path}")
    else:
        print(f"Directory already exists: {path}")

def create_file(path, content):
    """Create a file with the specified content."""
    with open(path, 'w', encoding='utf-8') as file:
        file.write(content)
    print(f"Created file: {path}")

def create_project_structure():
    """Create the complete project structure."""
    base_dir = "museum-system"
    
    # Create main directories
    directories = [
        f"{base_dir}",
        f"{base_dir}/docs",
        f"{base_dir}/docs/Structure",
        f"{base_dir}/docs/Structure/RPI",
        f"{base_dir}/docs/Structure/RPI/main",
        f"{base_dir}/raspberry_pi",
        f"{base_dir}/raspberry_pi/audio",
        f"{base_dir}/raspberry_pi/broker",
        f"{base_dir}/raspberry_pi/config",
        f"{base_dir}/raspberry_pi/logs",
        f"{base_dir}/raspberry_pi/scenes",
        f"{base_dir}/raspberry_pi/scenes/room1",
        f"{base_dir}/raspberry_pi/scenes/room2",
        f"{base_dir}/raspberry_pi/service",
        f"{base_dir}/raspberry_pi/tools",
        f"{base_dir}/raspberry_pi/tools/Blackscreen",
        f"{base_dir}/raspberry_pi/tools/DailyTasks",
        f"{base_dir}/raspberry_pi/tools/diagnostics",
        f"{base_dir}/raspberry_pi/tools/Monitoring",
        f"{base_dir}/raspberry_pi/utils",
        f"{base_dir}/raspberry_pi/videos",
        f"{base_dir}/raspberry_pi/Web",
        f"{base_dir}/raspberry_pi/Web/SceneGenerator",
        f"{base_dir}/raspberry_pi/Web/static",
        f"{base_dir}/raspberry_pi/Web/static/css",
        f"{base_dir}/raspberry_pi/Web/static/js",
        f"{base_dir}/esp32",
        f"{base_dir}/esp32/common",
        f"{base_dir}/esp32/devices",
        f"{base_dir}/esp32/devices/lan",
        f"{base_dir}/esp32/devices/wifi",
        f"{base_dir}/esp32/examples",
    ]
    
    for directory in directories:
        create_directory(directory)
    
    # Create main project files
    create_file(f"{base_dir}/README.md", "# Automated Museum with MQTT Control\n\n<!-- Add project description here -->")
    create_file(f"{base_dir}/TODO.txt", "# TODO List\n\n<!-- Add tasks here -->")
    
    # Documentation files
    create_file(f"{base_dir}/docs/architecture.md", "# Architecture Documentation\n\n<!-- Add architecture details here -->")
    create_file(f"{base_dir}/docs/audio_playing_tutorial.md", "# Audio Playing Tutorial\n\n<!-- Add audio tutorial here -->")
    create_file(f"{base_dir}/docs/mqtt_topics.md", "# MQTT Topics Documentation\n\n<!-- Add MQTT topics here -->")
    create_file(f"{base_dir}/docs/MQTT_topics_napad.md", "# MQTT Topics Ideas\n\n<!-- Add MQTT topic ideas here -->")
    create_file(f"{base_dir}/docs/museum_setup_guide.md", "# Museum Setup Guide\n\n<!-- Add setup guide here -->")
    create_file(f"{base_dir}/docs/video_player_tutorial.md", "# Video Player Tutorial\n\n<!-- Add video tutorial here -->")
    
    # Documentation structure flowchart files
    flowchart_files = [
        "dashboard_flowchart.py",
        "Flowchart_Main_Dashboard_Watchdog.py", 
        "full_flowchart.py",
        "logging_flowchart.py",
        "main_flowchart.py",
        "mqtt_flowchart.py",
        "scene_parser_flowchart.py",
        "watchdog_flowchart.py"
    ]
    
    for flowchart in flowchart_files:
        create_file(f"{base_dir}/docs/Structure/RPI/main/{flowchart}", "# Flowchart Generator\n\n# Put flowchart generation code here")
    
    # Create image placeholders (these would be generated by flowchart scripts)
    image_files = [
        "logging_flowchart.png.png",
        "mqtt_client_flowchart.png.png",
        "museum_controller_flowchart.png.png",
        "museum_system_flowchart_full.png.png",
        "museum_system_flowchart.png.png",
        "watchdog_flowchart.png.png",
        "web_flowchart.png.png"
    ]
    
    for image in image_files:
        create_file(f"{base_dir}/docs/Structure/RPI/{image}", "# This is a placeholder for generated flowchart image")
    
    # Raspberry Pi files
    create_file(f"{base_dir}/raspberry_pi/main.py", "#!/usr/bin/env python3\n# Main museum control script\n\n# Put main application code here")
    create_file(f"{base_dir}/raspberry_pi/watchdog.py", "#!/usr/bin/env python3\n# Watchdog service\n\n# Put watchdog code here")
    create_file(f"{base_dir}/raspberry_pi/requirements.txt", "# Python dependencies\n\n# Add required packages here")
    create_file(f"{base_dir}/raspberry_pi/setup_museum_service.sh", "#!/bin/bash\n# Setup script for museum service\n\n# Put setup commands here")
    
    # Audio files
    create_file(f"{base_dir}/raspberry_pi/audio/welcome.mp3", "# Audio file placeholder - replace with actual MP3 file")
    
    # Broker files
    create_file(f"{base_dir}/raspberry_pi/broker/mosquitto.conf", "# Mosquitto MQTT broker configuration\n\n# Put broker config here")
    create_file(f"{base_dir}/raspberry_pi/broker/start_broker.sh", "#!/bin/bash\n# Start MQTT broker script\n\n# Put broker startup commands here")
    
    # Config files
    create_file(f"{base_dir}/raspberry_pi/config/config.ini", "# Configuration file\n\n# Put configuration settings here")
    
    # Log files (empty placeholders)
    log_files = [
        "museum-daily.log",
        "museum-errors.log", 
        "museum.log",
        "museum-warnings.log"
    ]
    
    for log_file in log_files:
        create_file(f"{base_dir}/raspberry_pi/logs/{log_file}", "# Log file - will be populated by application")
    
    # Scene files
    create_file(f"{base_dir}/raspberry_pi/scenes/room1/intro.json", "{\n  \"_comment\": \"Put scene definition here\"\n}")
    create_file(f"{base_dir}/raspberry_pi/scenes/room1/test.json", "{\n  \"_comment\": \"Put test scene definition here\"\n}")
    create_file(f"{base_dir}/raspberry_pi/scenes/room1/wall.json", "{\n  \"_comment\": \"Put wall scene definition here\"\n}")
    create_file(f"{base_dir}/raspberry_pi/scenes/room2/intro.json", "{\n  \"_comment\": \"Put room2 scene definition here\"\n}")
    
    # Service files
    create_file(f"{base_dir}/raspberry_pi/service/museum_service.service", "# Systemd service file\n\n# Put service configuration here")
    create_file(f"{base_dir}/raspberry_pi/service/museum-watchdog.service", "# Systemd watchdog service file\n\n# Put watchdog service configuration here")
    
    # Tools - Blackscreen
    create_file(f"{base_dir}/raspberry_pi/tools/Blackscreen/TurnOff.bash", "#!/bin/bash\n# Turn off screen script\n\n# Put screen off commands here")
    create_file(f"{base_dir}/raspberry_pi/tools/Blackscreen/TurnOn.bash", "#!/bin/bash\n# Turn on screen script\n\n# Put screen on commands here")
    
    # Tools - DailyTasks
    create_file(f"{base_dir}/raspberry_pi/tools/DailyTasks/dailyreset.sh", "#!/bin/bash\n# Daily reset script\n\n# Put daily reset commands here")
    
    # Tools - Diagnostics
    diagnostic_files = [
        "permissionfix.sh",
        "restart_service.sh",
        "tempCodeRunnerFile.sh",
        "teststop.sh"
    ]
    
    for diag_file in diagnostic_files:
        create_file(f"{base_dir}/raspberry_pi/tools/diagnostics/{diag_file}", "#!/bin/bash\n# Diagnostic script\n\n# Put diagnostic commands here")
    
    # Tools - Monitoring
    create_file(f"{base_dir}/raspberry_pi/tools/Monitoring/health_check.sh", "#!/bin/bash\n# Health check script\n\n# Put health check commands here")
    create_file(f"{base_dir}/raspberry_pi/tools/Monitoring/RAMCheck.py", "#!/usr/bin/env python3\n# RAM monitoring script\n\n# Put RAM check code here")
    create_file(f"{base_dir}/raspberry_pi/tools/Monitoring/TaskManager.sh", "#!/bin/bash\n# Task manager script\n\n# Put task management commands here")
    create_file(f"{base_dir}/raspberry_pi/tools/Monitoring/temp_monitor.py", "#!/usr/bin/env python3\n# Temperature monitoring script\n\n# Put temperature monitoring code here")
    create_file(f"{base_dir}/raspberry_pi/tools/Monitoring/testifrunning.sh", "#!/bin/bash\n# Test if running script\n\n# Put running check commands here")
    
    # Utils
    util_files = [
        "audio_handler.py",
        "button_handler.py",
        "config_manager.py",
        "logging_setup.py",
        "mqtt_client.py",
        "scene_parser.py",
        "system_monitor.py",
        "video_handler.py"
    ]
    
    for util_file in util_files:
        create_file(f"{base_dir}/raspberry_pi/utils/{util_file}", "#!/usr/bin/env python3\n# Utility module\n\n# Put utility code here")
    
    # Videos
    create_file(f"{base_dir}/raspberry_pi/videos/black.png", "# Black screen image placeholder - replace with actual PNG file")
    create_file(f"{base_dir}/raspberry_pi/videos/ghost.mp4", "# Ghost video placeholder - replace with actual MP4 file")
    create_file(f"{base_dir}/raspberry_pi/videos/readme.md", "# Videos Directory\n\n<!-- Add video file descriptions here -->")
    
    # Web files
    create_file(f"{base_dir}/raspberry_pi/Web/dashboard.html", "<!DOCTYPE html>\n<html>\n<head>\n    <title>Museum Dashboard</title>\n</head>\n<body>\n    <!-- Put dashboard HTML here -->\n</body>\n</html>")
    create_file(f"{base_dir}/raspberry_pi/Web/web_dashboard.py", "#!/usr/bin/env python3\n# Web dashboard backend\n\n# Put web dashboard code here")
    create_file(f"{base_dir}/raspberry_pi/Web/stats.json", "{\n  \"_comment\": \"Put statistics data here\"\n}")
    
    # Web - SceneGenerator
    create_file(f"{base_dir}/raspberry_pi/Web/SceneGenerator/index.html", "<!DOCTYPE html>\n<html>\n<head>\n    <title>Scene Generator</title>\n</head>\n<body>\n    <!-- Put scene generator HTML here -->\n</body>\n</html>")
    create_file(f"{base_dir}/raspberry_pi/Web/SceneGenerator/script.js", "// Scene generator JavaScript\n\n// Put JavaScript code here")
    create_file(f"{base_dir}/raspberry_pi/Web/SceneGenerator/styles.css", "/* Scene generator CSS */\n\n/* Put CSS styles here */")
    
    # Web - Static files
    css_files = [
        "base.css",
        "components.css", 
        "layout.css",
        "utilities.css"
    ]
    
    for css_file in css_files:
        create_file(f"{base_dir}/raspberry_pi/Web/static/css/{css_file}", "/* CSS Stylesheet */\n\n/* Put CSS styles here */")
    
    create_file(f"{base_dir}/raspberry_pi/Web/static/js/script.js", "// Main JavaScript file\n\n// Put JavaScript code here")
    
    # ESP32 files
    create_file(f"{base_dir}/esp32/common/WifiCheck.ino", "/*\n * WiFi Check Arduino sketch\n * \n * Put WiFi checking code here\n */")
    
    # ESP32 devices
    create_file(f"{base_dir}/esp32/devices/lan/light_controller.ino", "/*\n * Light Controller Arduino sketch (LAN)\n * \n * Put light controller code here\n */")
    create_file(f"{base_dir}/esp32/devices/wifi/WallController.ino", "/*\n * Wall Controller Arduino sketch (WiFi)\n * \n * Put wall controller code here\n */")
    
    # Create .gitignore to exclude __pycache__ and other files
    gitignore_content = """# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
env/
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
*.egg-info/
.installed.cfg
*.egg

# Arduino
.pioenvs
.piolibdeps
.clang_complete
.gcc-flags.json

# Editors
.vscode/
.idea/
*.swp
*.swo

# OS specific
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db

# Project specific
mosquitto.db
*.log

# Generated images
*.png
*.jpg
*.jpeg
*.gif
"""
    create_file(f"{base_dir}/.gitignore", gitignore_content)
    
    # Make shell scripts executable
    shell_scripts = [
        f"{base_dir}/raspberry_pi/broker/start_broker.sh",
        f"{base_dir}/raspberry_pi/setup_museum_service.sh",
        f"{base_dir}/raspberry_pi/tools/Blackscreen/TurnOff.bash",
        f"{base_dir}/raspberry_pi/tools/Blackscreen/TurnOn.bash",
        f"{base_dir}/raspberry_pi/tools/DailyTasks/dailyreset.sh",
        f"{base_dir}/raspberry_pi/tools/diagnostics/permissionfix.sh",
        f"{base_dir}/raspberry_pi/tools/diagnostics/restart_service.sh",
        f"{base_dir}/raspberry_pi/tools/diagnostics/tempCodeRunnerFile.sh",
        f"{base_dir}/raspberry_pi/tools/diagnostics/teststop.sh",
        f"{base_dir}/raspberry_pi/tools/Monitoring/health_check.sh",
        f"{base_dir}/raspberry_pi/tools/Monitoring/TaskManager.sh",
        f"{base_dir}/raspberry_pi/tools/Monitoring/testifrunning.sh",
    ]
    
    for script in shell_scripts:
        if os.path.exists(script):
            os.chmod(script, 0o755)
    
    print("\nProject structure created successfully!")
    print(f"Project created at: {os.path.abspath(base_dir)}")
    print("\nStructure includes:")
    print("- Complete directory structure")
    print("- Blank files with comments indicating where to add code")
    print("- Proper file extensions and permissions")
    print("- .gitignore to exclude __pycache__ and other generated files")
    print("\nNote: __pycache__ directories are not created as they are generated automatically by Python")
    print("and should be excluded from version control.")

if __name__ == "__main__":
    create_project_structure()