import graphviz

# Create a Graphviz flowchart for the complete museum system
dot = graphviz.Digraph(comment='Museum System Flowchart', format='png')

# Define node styles
dot.attr('node', shape='box', style='filled', fillcolor='lightblue', fontsize='12')
dot.attr('edge', fontsize='10')

# Main Controller Nodes
dot.node('A', 'Start main.py')
dot.node('B', 'Setup Logging\n(museum.log, warnings,\nerrors, daily)', fillcolor='lightyellow')
dot.node('C', 'Initialize MuseumController\n(Load Config, Setup Components)')
dot.node('D', 'Start Web Dashboard\n(Flask, SocketIO)', fillcolor='lightgreen')
dot.node('E', 'Start Watchdog\n(Monitor Process)', fillcolor='lightcoral')
dot.node('F', 'Test MQTT Connection', shape='diamond', fillcolor='yellow')
dot.node('G', 'Exit (Critical Error)\n(Log Critical)', shape='ellipse', fillcolor='red')
dot.node('H', 'Send Ready Notification\n(Log Info)')
dot.node('I', 'Main Run Loop')
dot.node('J', 'Perform Health Check\n(Log if Unhealthy)')
dot.node('K', 'MQTT Connected?', shape='diamond', fillcolor='yellow')
dot.node('L', 'Log Warning\n(MQTT Lost)')
dot.node('M', 'Log Info\n(MQTT Restored)')
dot.node('N', 'Button Polling Enabled?', shape='diamond', fillcolor='yellow')
dot.node('O', 'Check Button Press', fillcolor='lightblue')
dot.node('P', 'Scene Running?', shape='diamond', fillcolor='yellow')
dot.node('Q', 'Log Warning\n(Scene Already Running)')
dot.node('R', 'Start Default Scene')
dot.node('S', 'Scene File Exists?', shape='diamond', fillcolor='yellow')
dot.node('T', 'Create Default Scene\n(Log Info)')
dot.node('U', 'Load Scene')
dot.node('V', 'Scene Loaded?', shape='diamond', fillcolor='yellow')
dot.node('W', 'MQTT Connected for Scene?', shape='diamond', fillcolor='yellow')  # New node
dot.node('X', 'Run Scene\n(Execute Actions, Log Info)')
dot.node('Y', 'Log Error\n(Scene Load Failed)')
dot.node('Z', 'Skip Scene\n(Wait for Reconnection, Log Error)')
dot.node('AA', 'Shutdown Requested?', shape='diamond', fillcolor='yellow')
dot.node('AB', 'Cleanup\n(Button, Audio, MQTT, Log Info)')
dot.node('AC', 'Exit', shape='ellipse', fillcolor='red')

# Web Dashboard Nodes
dot.node('AD', 'Setup Dashboard\n(Add WebLogHandler)', fillcolor='lightgreen')
dot.node('AE', 'Setup Routes\n(/status, /logs, /scenes,\n/run_scene, /stop_scene, /restart)', fillcolor='lightgreen')
dot.node('AF', 'Load Existing Logs\n(from museum.log)', fillcolor='lightgreen')
dot.node('AG', 'Handle Client Connection\n(Emit Log History, Status)', shape='diamond', fillcolor='yellow')
dot.node('AH', 'Handle Web Request', shape='diamond', fillcolor='yellow')
dot.node('AI', 'Run Scene Request?', shape='diamond', fillcolor='yellow')
dot.node('AJ', 'Trigger Scene\n(Load and Run, Log Info)', fillcolor='lightgreen')
dot.node('AK', 'Other Request\n(Stop Scene, Restart, Logs, Status)', fillcolor='lightgreen')
dot.node('AL', 'Process Request\n(Update Log Buffer)', fillcolor='lightgreen')
dot.node('AM', 'Broadcast Log\n(via SocketIO)', fillcolor='lightgreen')

# Watchdog Nodes
dot.node('AN', 'Start Watchdog', fillcolor='lightcoral')
dot.node('AO', 'Setup Watchdog Logging\n(museum.log, warnings, errors)', fillcolor='lightcoral')
dot.node('AP', 'Initialize Watchdog\n(Set CPU/Mem Thresholds)', fillcolor='lightcoral')
dot.node('AQ', 'Watchdog Loop', fillcolor='lightcoral')
dot.node('AR', 'Service Running?', shape='diamond', fillcolor='yellow')
dot.node('AS', 'Start/Restart Service\n(Log Warning)', fillcolor='lightcoral')
dot.node('AT', 'Check Process Health\n(CPU > 45%, Mem > 512MB)', shape='diamond', fillcolor='yellow')
dot.node('AU', 'Process Healthy?', shape='diamond', fillcolor='yellow')
dot.node('AV', 'Check Network\n(Log Warning if Lost)', fillcolor='lightcoral')
dot.node('AW', 'Log Health Status\n(CPU, Mem, if Needed)', fillcolor='lightcoral')

# MQTT Nodes
dot.node('AX', 'Initialize MQTT Client\n(Set Callbacks)', fillcolor='lightcyan')
dot.node('AY', 'Connect to Broker', shape='diamond', fillcolor='yellow')
dot.node('AZ', 'Connection Successful?', shape='diamond', fillcolor='yellow')
dot.node('BA', 'Try Localhost Fallback', fillcolor='lightcyan')
dot.node('BB', 'Publish/Subscribe\n(Log Info)', fillcolor='lightcyan')

# Logging Nodes
dot.node('BC', 'Setup Logging\n(Console, Files: museum.log,\nwarnings, errors, daily)', fillcolor='lightyellow')
dot.node('BD', 'Add Handlers\n(Rotating, Daily, Level Filters)', fillcolor='lightyellow')
dot.node('BE', 'Log Startup Message', fillcolor='lightyellow')

# Add edges with labels to show flow and decisions
dot.edge('A', 'B', label='Start')
dot.edge('B', 'C', label='Setup Logging')
dot.edge('C', 'D', label='Start Dashboard Thread', style='dashed')
dot.edge('C', 'E', label='Start Watchdog Thread', style='dashed')
dot.edge('C', 'F', label='Initialize Controller')
dot.edge('D', 'AD', label='Initialize Dashboard', style='dashed')
dot.edge('AD', 'AE', label='Setup Logging')
dot.edge('AE', 'AF', label='Setup Routes')
dot.edge('AF', 'AG', label='Load Logs')
dot.edge('AG', 'AH', label='Client Connected')
dot.edge('AH', 'AI', label='Receive Request')
dot.edge('AI', 'AJ', label='Yes')
dot.edge('AI', 'AK', label='No')
dot.edge('AJ', 'AL', label='Trigger Scene')
dot.edge('AK', 'AL', label='Process')
dot.edge('AL', 'AM', label='Update')
dot.edge('AM', 'AA', label='Broadcast Log')
dot.edge('E', 'AN', label='Initialize Watchdog', style='dashed')
dot.edge('AN', 'AO', label='Start')
dot.edge('AO', 'AP', label='Setup Logging')
dot.edge('AP', 'AQ', label='Set Thresholds')
dot.edge('AQ', 'AR', label='Periodic Check')
dot.edge('AR', 'AS', label='No')
dot.edge('AR', 'AT', label='Yes')
dot.edge('AT', 'AU', label='Check Health')
dot.edge('AU', 'AS', label='No (High CPU/Mem)')
dot.edge('AU', 'AV', label='Yes')
dot.edge('AV', 'AW', label='Check Network')
dot.edge('AW', 'AQ', label='Log (if needed)', style='dashed')
dot.edge('AS', 'A', label='Restart', style='dashed')
dot.edge('F', 'AX', label='Setup MQTT')
dot.edge('AX', 'AY', label='Initialize')
dot.edge('AY', 'AZ', label='Attempt Connect')
dot.edge('AZ', 'H', label='Yes')
dot.edge('AZ', 'BA', label='No')
dot.edge('BA', 'AY', label='Try Again')
dot.edge('BA', 'G', label='Failed')
dot.edge('H', 'I', label='System Ready')
dot.edge('I', 'J', label='Periodic Check')
dot.edge('J', 'K', label='Health Check')
dot.edge('K', 'L', label='No')
dot.edge('K', 'M', label='Yes')
dot.edge('L', 'N', label='Log Warning')
dot.edge('M', 'N', label='Log Info')
dot.edge('N', 'O', label='Yes')
dot.edge('N', 'AA', label='No')
dot.edge('O', 'P', label='Check Button')
dot.edge('P', 'Q', label='Yes')
dot.edge('P', 'R', label='No')
dot.edge('R', 'S', label='Start Scene')
dot.edge('S', 'T', label='No')
dot.edge('S', 'U', label='Yes')
dot.edge('T', 'U', label='Created')
dot.edge('U', 'V', label='Load')
dot.edge('V', 'W', label='Success')
dot.edge('V', 'Y', label='Failed')
dot.edge('W', 'X', label='Yes')
dot.edge('W', 'Z', label='No')  # New edge for MQTT check failure
dot.edge('X', 'AA', label='Yes')  # Proceed to shutdown check if scene runs
dot.edge('Z', 'AA', label='Skip Scene, Wait')  # New edge for skipping scene
dot.edge('Q', 'AA', label='Ignore')
dot.edge('Y', 'AA', label='Error Logged')
dot.edge('AA', 'I', label='No', style='dashed')
dot.edge('AA', 'AB', label='Yes')
dot.edge('AB', 'AC', label='Cleanup Done')
dot.edge('B', 'BC', label='Initialize Logging', style='dashed')
dot.edge('BC', 'BD', label='Setup')
dot.edge('BD', 'BE', label='Add Handlers')
dot.edge('BE', 'C', label='Log Startup')

# Add styling for clarity and presentation
dot.attr(dpi='400', fontsize='12', labelloc='t', label='Museum System Flowchart\n(Controller, Dashboard, Watchdog, Logging, MQTT)', labeljust='c')
dot.attr(bgcolor='lightgrey', rankdir='TB', splines='polyline')

# Render the flowchart
dot.render('/home/admin/Documents/GitHub/museum-system/docs/Structure/RPI/museum_system_flowchart.png', view=False)