import graphviz

# Create a Graphviz flowchart for the complete museum system
dot = graphviz.Digraph(comment='Museum System Flowchart', format='png')

# Define node styles
dot.attr('node', shape='box', style='filled', fillcolor='lightblue', fontsize='12')
dot.attr('edge', fontsize='10')

# Main Controller Nodes (main.py)
dot.node('A', 'Start main.py')
dot.node('B', 'Setup Logging\n(logging_setup.py)', fillcolor='lightyellow')
dot.node('C', 'Initialize MuseumController\n(Load Config, Setup Components)')
dot.node('D', 'Start Web Dashboard\n(web_dashboard.py)', fillcolor='lightgreen')
dot.node('E', 'Start Watchdog\n(watchdog.py)', fillcolor='lightcoral')
dot.node('F', 'Test MQTT Connection\n(mqtt_client.py)', shape='diamond', fillcolor='yellow')
dot.node('G', 'Exit (Critical Error)\n(Log Critical)', shape='ellipse', fillcolor='red')
dot.node('H', 'Send Ready Notification\n(system_monitor.py)')
dot.node('I', 'Main Run Loop')
dot.node('J', 'Perform Health Check\n(system_monitor.py)')
dot.node('K', 'MQTT Connected?', shape='diamond', fillcolor='yellow')
dot.node('L', 'Log Warning\n(MQTT Lost)')
dot.node('M', 'Log Info\n(MQTT Restored)')
dot.node('N', 'Button Polling Enabled?', shape='diamond', fillcolor='yellow')
dot.node('O', 'Check Button Press\n(button_handler.py)')
dot.node('P', 'Scene Running?', shape='diamond', fillcolor='yellow')
dot.node('Q', 'Log Warning\n(Scene Already Running)')
dot.node('R', 'Start Default Scene\n(scene_parser.py)')
dot.node('S', 'Scene File Exists?', shape='diamond', fillcolor='yellow')
dot.node('T', 'Create Default Scene\n(JSON with Light/Audio Actions)')
dot.node('U', 'Load Scene\n(scene_parser.py)')
dot.node('V', 'Scene Loaded?', shape='diamond', fillcolor='yellow')
dot.node('W', 'MQTT Connected for Scene?', shape='diamond', fillcolor='yellow')
dot.node('X', 'Run Scene\n(Execute Actions, Log Info)')
dot.node('Y', 'Log Error\n(Scene Load Failed)')
dot.node('Z', 'Skip Scene\n(Wait for Reconnection, Log Error)')
dot.node('AA', 'Shutdown Requested?', shape='diamond', fillcolor='yellow')
dot.node('AB', 'Cleanup\n(Button, Audio, MQTT, Log Info)')
dot.node('AC', 'Exit', shape='ellipse', fillcolor='red')

# Web Dashboard Nodes (web_dashboard.py, dashboard.html)
dot.node('AD', 'Setup Dashboard\n(Add WebLogHandler, Flask, SocketIO)', fillcolor='lightgreen')
dot.node('AE', 'Setup Routes\n(/status, /logs, /scenes, /run_scene, /stop_scene, /restart)', fillcolor='lightgreen')
dot.node('AF', 'Load Existing Logs\n(from museum.log)', fillcolor='lightgreen')
dot.node('AG', 'Handle Client Connection\n(Emit Log History, Status)', shape='diamond', fillcolor='yellow')
dot.node('AH', 'Handle Web Request\n(scene_parser.py)', shape='diamond', fillcolor='yellow')
dot.node('AI', 'Run Scene Request?', shape='diamond', fillcolor='yellow')
dot.node('AJ', 'Trigger Scene\n(Load and Run, Log Info)', fillcolor='lightgreen')
dot.node('AK', 'Other Request\n(Stop Scene, Restart, Logs, Status)', fillcolor='lightgreen')
dot.node('AL', 'Process Request\n(Update Log Buffer, dashboard.html)', fillcolor='lightgreen')
dot.node('AM', 'Broadcast Log\n(via SocketIO)', fillcolor='lightgreen')

# Watchdog Nodes (watchdog.py)
dot.node('AN', 'Start Watchdog', fillcolor='lightcoral')
dot.node('AO', 'Setup Watchdog Logging\n(museum.log, warnings, errors)', fillcolor='lightcoral')
dot.node('AP', 'Initialize Watchdog\n(Set CPU/Mem Thresholds)', fillcolor='lightcoral')
dot.node('AQ', 'Watchdog Loop')
dot.node('AR', 'Service Running?', shape='diamond', fillcolor='yellow')
dot.node('AS', 'Start/Restart Service\n(Log Warning)', fillcolor='lightcoral')
dot.node('AT', 'Check Process Health\n(CPU > 45%, Mem > 512MB)', shape='diamond', fillcolor='yellow')
dot.node('AU', 'Process Healthy?', shape='diamond', fillcolor='yellow')
dot.node('AV', 'Check Network\n(Log Warning if Lost)', fillcolor='lightcoral')
dot.node('AW', 'Log Health Status\n(CPU, Mem, if Needed)', fillcolor='lightcoral')

# MQTT Nodes (mqtt_client.py)
dot.node('AX', 'Initialize MQTT Client\n(Set Callbacks, paho-mqtt)', fillcolor='lightcyan')
dot.node('AY', 'Connect to Broker', shape='diamond', fillcolor='yellow')
dot.node('AZ', 'Connection Successful?', shape='diamond', fillcolor='yellow')
dot.node('BA', 'Try Localhost Fallback', fillcolor='lightcyan')
dot.node('BB', 'Publish/Subscribe\n(Log Info)', fillcolor='lightcyan')

# Logging Nodes (logging_setup.py)
dot.node('BC', 'Setup Logging\n(Console, Files: museum.log,\nwarnings, errors, daily)', fillcolor='lightyellow')
dot.node('BD', 'Add Handlers\n(Rotating, Daily, Level Filters)', fillcolor='lightyellow')
dot.node('BE', 'Log Startup Message', fillcolor='lightyellow')

# Configuration Nodes (config_manager.py)
dot.node('BF', 'Initialize ConfigManager\n(config.ini)', fillcolor='lightgoldenrodyellow')
dot.node('BG', 'Config File Exists?', shape='diamond', fillcolor='yellow')
dot.node('BH', 'Create Default Config\n(MQTT, GPIO, Room, Scenes, Audio)', fillcolor='lightgoldenrodyellow')
dot.node('BI', 'Load Config\n(Return All Config)', fillcolor='lightgoldenrodyellow')

# Audio Nodes (audio_handler.py)
dot.node('BJ', 'Initialize AudioHandler\n(pygame.mixer)', fillcolor='lightpink')
dot.node('BK', 'Handle Audio Command\n(PLAY, STOP, PAUSE, VOLUME)', fillcolor='lightpink')
dot.node('BL', 'Play Audio\n(Supports .wav, .mp3, .ogg)', fillcolor='lightpink')
dot.node('BM', 'List Audio Files\n(Log if Not Found)', fillcolor='lightpink')

# Add edges with labels to show flow and decisions
dot.edge('A', 'B', label='Start')
dot.edge('B', 'C', label='Setup Logging')
dot.edge('C', 'BF', label='Load Config')
dot.edge('BF', 'BG', label='Initialize Config')
dot.edge('BG', 'BH', label='No')
dot.edge('BG', 'BI', label='Yes')
dot.edge('BH', 'BI', label='Created')
dot.edge('BI', 'D', label='Config Loaded', style='dashed')
dot.edge('BI', 'E', label='Start Watchdog', style='dashed')
dot.edge('BI', 'F', label='Initialize Components')
dot.edge('D', 'AD', label='Initialize Dashboard', style='dashed')
dot.edge('AD', 'AE', label='Setup Logging')
dot.edge('AE', 'AF', label='Setup Routes')
dot.edge('AF', 'AG', label='Load Logs')
dot.edge('AG', 'AH', label='Client Connected')
dot.edge('AH', 'AI', label='Receive Request')
dot.edge('AI', 'AJ', label='Yes')
dot.edge('AI', 'AK', label='No')
dot.edge('AJ', 'AL', label='Trigger Scene')
dot.edge('AK', 'AL', label='Process')
dot.edge('AL', 'AM', label='Update')
dot.edge('AM', 'AA', label='Broadcast Log')
dot.edge('E', 'AN', label='Initialize Watchdog', style='dashed')
dot.edge('AN', 'AO', label='Start')
dot.edge('AO', 'AP', label='Setup Logging')
dot.edge('AP', 'AQ', label='Set Thresholds')
dot.edge('AQ', 'AR', label='Periodic Check')
dot.edge('AR', 'AS', label='No')
dot.edge('AR', 'AT', label='Yes')
dot.edge('AT', 'AU', label='Check Health')
dot.edge('AU', 'AS', label='No (High CPU/Mem)')
dot.edge('AU', 'AV', label='Yes')
dot.edge('AV', 'AW', label='Check Network')
dot.edge('AW', 'AQ', label='Log (if needed)', style='dashed')
dot.edge('AS', 'A', label='Restart', style='dashed')
dot.edge('F', 'AX', label='Setup MQTT')
dot.edge('AX', 'AY', label='Initialize')
dot.edge('AY', 'AZ', label='Attempt Connect')
dot.edge('AZ', 'H', label='Yes')
dot.edge('AZ', 'BA', label='No')
dot.edge('BA', 'AY', label='Try Again')
dot.edge('BA', 'G', label='Failed')
dot.edge('H', 'I', label='System Ready')
dot.edge('I', 'J', label='Periodic Check')
dot.edge('J', 'K', label='Health Check')
dot.edge('K', 'L', label='No')
dot.edge('K', 'M', label='Yes')
dot.edge('L', 'N', label='Log Warning')
dot.edge('M', 'N', label='Log Info')
dot.edge('N', 'O', label='Yes')
dot.edge('N', 'AA', label='No')
dot.edge('O', 'P', label='Check Button')
dot.edge('P', 'Q', label='Yes')
dot.edge('P', 'R', label='No')
dot.edge('R', 'S', label='Start Scene')
dot.edge('S', 'T', label='No')
dot.edge('S', 'U', label='Yes')
dot.edge('T', 'U', label='Created')
dot.edge('U', 'V', label='Load')
dot.edge('V', 'W', label='Success')
dot.edge('V', 'Y', label='Failed')
dot.edge('W', 'X', label='Yes')
dot.edge('W', 'Z', label='No')
dot.edge('X', 'BK', label='Handle Audio', style='dashed')
dot.edge('BK', 'BL', label='Play/Stop/Pause')
dot.edge('BL', 'AA', label='Action Done')
dot.edge('Z', 'AA', label='Skip Scene')
dot.edge('Q', 'AA', label='Ignore')
dot.edge('Y', 'AA', label='Error Civilian')
dot.edge('AA', 'I', label='No', style='dashed')
dot.edge('AA', 'AB', label='Yes')
dot.edge('AB', 'AC', label='Cleanup Done')
dot.edge('B', 'BC', label='Initialize Logging', style='dashed')
dot.edge('BC', 'BD', label='Setup')
dot.edge('BD', 'BE', label='Add Handlers')
dot.edge('BE', 'C', label='Log Startup')
dot.edge('U', 'BM', label='List Audio Files', style='dashed')

# Add styling for clarity and presentation
dot.attr(dpi='400', fontsize='12', labelloc='t', label='Museum System Flowchart\n(Controller, Dashboard, Watchdog, MQTT, Config, Audio, Logging)', labeljust='c')
dot.attr(bgcolor='lightgrey', rankdir='TB', splines='polyline')

# Render the flowchart
dot.render('/home/admin/Documents/GitHub/museum-system/docs/Structure/RPI/museum_system_flowchart_full.png', view=False)