import graphviz

# Create a Graphviz flowchart for the MuseumController in main.py
dot = graphviz.Digraph(comment='Museum Controller Flowchart', format='png')

# Define node styles
dot.attr('node', shape='box', style='filled', fillcolor='lightblue', fontsize='12')
dot.attr('edge', fontsize='10')

# Main Controller Nodes
dot.node('A', 'Start main.py')
dot.node('B', 'Setup Logging\n(museum.log)', fillcolor='lightyellow')
dot.node('C', 'Initialize MuseumController\n(Load Config, Setup Components)')
dot.node('D', 'Test MQTT Connection', shape='diamond', fillcolor='yellow')
dot.node('E', 'Exit (Critical Error)\n(Log Critical)', shape='ellipse', fillcolor='red')
dot.node('F', 'Send Ready Notification\n(Log Info)')
dot.node('G', 'Main Run Loop')
dot.node('H', 'Perform Health Check\n(Log if Unhealthy)')
dot.node('I', 'MQTT Connected?', shape='diamond', fillcolor='yellow')
dot.node('J', 'Log Warning\n(MQTT Lost)')
dot.node('K', 'Log Info\n(MQTT Restored)')
dot.node('L', 'Button Polling Enabled?', shape='diamond', fillcolor='yellow')
dot.node('M', 'Check Button Press', fillcolor='lightblue')
dot.node('N', 'Scene Running?', shape='diamond', fillcolor='yellow')
dot.node('O', 'Log Warning\n(Scene Already Running)')
dot.node('P', 'MQTT Connected for Scene?', shape='diamond', fillcolor='yellow')
dot.node('Q', 'Log Error\n(MQTT Not Connected)')
dot.node('R', 'Scene File Exists?', shape='diamond', fillcolor='yellow')
dot.node('S', 'Create Default Scene\n(Log Info)')
dot.node('T', 'Load Scene')
dot.node('U', 'Scene Loaded?', shape='diamond', fillcolor='yellow')
dot.node('V', 'Run Scene\n(Execute Actions, Log Info)')
dot.node('W', 'Log Error\n(Scene Load Failed)')
dot.node('X', 'Shutdown Requested?', shape='diamond', fillcolor='yellow')
dot.node('Y', 'Cleanup\n(Button, Audio, MQTT, Log Info)')
dot.node('Z', 'Exit', shape='ellipse', fillcolor='red')

# MQTT Nodes
dot.node('AA', 'Initialize MQTT Client', fillcolor='lightcyan')
dot.node('AB', 'Connect to Broker', shape='diamond', fillcolor='yellow')
dot.node('AC', 'Connection Successful?', shape='diamond', fillcolor='yellow')
dot.node('AD', 'Try Localhost Fallback', fillcolor='lightcyan')

# Logging Nodes
dot.node('AE', 'Setup Logging\n(Console, File: museum.log)', fillcolor='lightyellow')
dot.node('AF', 'Log Startup Message', fillcolor='lightyellow')

# Add edges with labels to show flow and decisions
dot.edge('A', 'B', label='Start')
dot.edge('B', 'AE', label='Initialize Logging')
dot.edge('AE', 'AF', label='Setup')
dot.edge('AF', 'C', label='Log Startup')
dot.edge('C', 'D', label='Initialize Controller')
dot.edge('D', 'AA', label='Setup MQTT')
dot.edge('AA', 'AB', label='Initialize')
dot.edge('AB', 'AC', label='Attempt Connect')
dot.edge('AC', 'F', label='Yes')
dot.edge('AC', 'AD', label='No')
dot.edge('AD', 'AB', label='Try Again')
dot.edge('AD', 'E', label='Failed')
dot.edge('F', 'G', label='System Ready')
dot.edge('G', 'H', label='Periodic Check')
dot.edge('H', 'I', label='Health Check')
dot.edge('I', 'J', label='No')
dot.edge('I', 'K', label='Yes')
dot.edge('J', 'L', label='Log Warning')
dot.edge('K', 'L', label='Log Info')
dot.edge('L', 'M', label='Yes')
dot.edge('L', 'X', label='No')
dot.edge('M', 'N', label='Check Button')
dot.edge('N', 'O', label='Yes')
dot.edge('N', 'P', label='No')
dot.edge('P', 'Q', label='No')
dot.edge('P', 'R', label='Yes')
dot.edge('Q', 'X', label='Skip Scene')
dot.edge('R', 'S', label='No')
dot.edge('R', 'T', label='Yes')
dot.edge('S', 'T', label='Created')
dot.edge('T', 'U', label='Load')
dot.edge('U', 'V', label='Yes')
dot.edge('U', 'W', label='No')
dot.edge('V', 'X', label='Run Scene')
dot.edge('W', 'X', label='Error Logged')
dot.edge('O', 'X', label='Ignore')
dot.edge('X', 'G', label='No', style='dashed')
dot.edge('X', 'Y', label='Yes')
dot.edge('Y', 'Z', label='Cleanup Done')

# Add styling for clarity and presentation
dot.attr(dpi='400', fontsize='12', labelloc='t', label='Museum Controller Flowchart\n(Main Controller, MQTT, Logging)', labeljust='c')
dot.attr(bgcolor='lightgrey', rankdir='TB', splines='polyline')

# Render the flowchart
dot.render('/home/admin/Documents/GitHub/museum-system/docs/Structure/RPI/museum_controller_flowchart.png', view=False)