import graphviz

# Create a simplified Graphviz flowchart for the SceneParser class
dot = graphviz.Digraph(comment='Scene Parser Flowchart', format='png')

# Define node styles
dot.attr('node', shape='box', style='filled', fillcolor='lightblue', fontsize='12')
dot.attr('edge', fontsize='10')

# Main nodes
dot.node('A', 'Initialize SceneParser\n(audio_handler, logger)')
dot.node('B', 'Load Scene\n(scene_file)', fillcolor='lightyellow')
dot.node('C', 'Valid Scene File?', shape='diamond', fillcolor='yellow')
dot.node('D', 'Load & Validate JSON\n(Requires timestamp, topic, message)', fillcolor='lightyellow')
dot.node('E', 'Valid Data?', shape='diamond', fillcolor='yellow')
dot.node('F', 'Log Success\nReset Executed Actions', fillcolor='lightgreen')
dot.node('G', 'Log Error\n(Failed to Load Scene)', fillcolor='red')
dot.node('H', 'Start Scene')
dot.node('I', 'Scene Loaded?', shape='diamond', fillcolor='yellow')
dot.node('J', 'Log Error\n(No Scene Loaded)', fillcolor='red')
dot.node('K', 'Set Start Time\nReset Executed Actions', fillcolor='lightgreen')
dot.node('L', 'Get Current Actions\n(mqtt_client)')
dot.node('M', 'Scene Ready?', shape='diamond', fillcolor='yellow')
dot.node('N', 'Return Empty List')
dot.node('O', 'Check Actions\n(Timestamp ≤ Current Time\nand Not Executed)', shape='diamond', fillcolor='yellow')
dot.node('P', 'Process Action')
dot.node('Q', 'Audio Command?', shape='diamond', fillcolor='yellow')
dot.node('R', 'Handle Audio\n(PLAY, STOP, PAUSE, VOLUME)', fillcolor='lightpink')
dot.node('S', 'Publish to MQTT')
dot.node('T', 'Mark Action Executed')
dot.node('U', 'Get Scene Duration')
dot.node('V', 'Scene Loaded?', shape='diamond', fillcolor='yellow')
dot.node('W', 'Return 0')
dot.node('X', 'Return Max Timestamp', fillcolor='lightgreen')
dot.node('Y', 'Get Scene Progress')
dot.node('Z', 'Scene Ready?', shape='diamond', fillcolor='yellow')
dot.node('AA', 'Return 0.0')
dot.node('AB', 'Calculate Progress\n(Current Time / Duration)', fillcolor='lightgreen')
dot.node('AC', 'Is Scene Complete?', shape='diamond', fillcolor='yellow')
dot.node('AD', 'Scene Ready?', shape='diamond', fillcolor='yellow')
dot.node('AE', 'Return False')
dot.node('AF', 'Time > Duration?', shape='diamond', fillcolor='yellow')
dot.node('AG', 'Return True', fillcolor='lightgreen')
dot.node('AH', 'Main Program\n(Setup Paths, AudioHandler, MQTTClient)')
dot.node('AI', 'Load Scene')
dot.node('AJ', 'Scene Loaded?', shape='diamond', fillcolor='yellow')
dot.node('AK', 'Log Success\nShow Duration', fillcolor='lightgreen')
dot.node('AL', 'Log Error\n(Failed to Load Scene)', fillcolor='red')
dot.node('AM', 'Connect to MQTT?', shape='diamond', fillcolor='yellow')
dot.node('AN', 'Log Success\n(MQTT Connected)', fillcolor='lightgreen')
dot.node('AO', 'Log Warning\n(Simulation Mode)')
dot.node('AP', 'Start Scene')
dot.node('AQ', 'Scene Playback Loop')
dot.node('AR', 'Execute Actions')
dot.node('AS', 'Actions to Execute?', shape='diamond', fillcolor='yellow')
dot.node('AT', 'Log Progress & Actions', fillcolor='lightgreen')
dot.node('AU', 'Scene Complete?', shape='diamond', fillcolor='yellow')
dot.node('AV', 'Cleanup\n(MQTT, Audio)', fillcolor='lightgreen')
dot.node('AW', 'Log Error\n(Import Failure)', fillcolor='red')

# Add edges
dot.edge('A', 'B', label='Load Scene')
dot.edge('B', 'C', label='Call load_scene')
dot.edge('C', 'D', label='Yes')
dot.edge('C', 'G', label='No')
dot.edge('D', 'E', label='Load JSON')
dot.edge('E', 'F', label='Valid')
dot.edge('E', 'G', label='Invalid')
dot.edge('F', 'H', label='Success')
dot.edge('H', 'I', label='Call start_scene')
dot.edge('I', 'J', label='No')
dot.edge('I', 'K', label='Yes')
dot.edge('K', 'L', label='Start')
dot.edge('L', 'M', label='Call get_current_actions')
dot.edge('M', 'N', label='No')
dot.edge('M', 'O', label='Yes')
dot.edge('O', 'P', label='Yes')
dot.edge('O', 'L', label='No', style='dashed')
dot.edge('P', 'Q', label='Process')
dot.edge('Q', 'R', label='Yes')
dot.edge('Q', 'S', label='No')
dot.edge('R', 'T', label='Execute')
dot.edge('S', 'T', label='Publish')
dot.edge('T', 'L', label='Continue', style='dashed')
dot.edge('U', 'V', label='Call get_scene_duration')
dot.edge('V', 'W', label='No')
dot.edge('V', 'X', label='Yes')
dot.edge('X', 'Y', label='Return Duration')
dot.edge('Y', 'Z', label='Call get_scene_progress')
dot.edge('Z', 'AA', label='No')
dot.edge('Z', 'AB', label='Yes')
dot.edge('AB', 'AC', label='Return Progress')
dot.edge('AC', 'AD', label='Call is_scene_complete')
dot.edge('AD', 'AE', label='No')
dot.edge('AD', 'AF', label='Yes')
dot.edge('AF', 'AG', label='Yes')
dot.edge('AF', 'AE', label='No')
dot.edge('AH', 'AI', label='Start')
dot.edge('AI', 'AJ', label='Load Scene')
dot.edge('AJ', 'AK', label='Yes')
dot.edge('AJ', 'AL', label='No')
dot.edge('AK', 'AM', label='Success')
dot.edge('AM', 'AN', label='Yes')
dot.edge('AM', 'AO', label='No')
dot.edge('AN', 'AP', label='Connected')
dot.edge('AO', 'AP', label='Simulation')
dot.edge('AP', 'AQ', label='Start Scene')
dot.edge('AQ', 'AR', label='Loop')
dot.edge('AR', 'AS', label='Get Actions')
dot.edge('AS', 'AT', label='Yes')
dot.edge('AS', 'AU', label='No')
dot.edge('AT', 'AU', label='Log Actions')
dot.edge('AU', 'AV', label='Yes')
dot.edge('AU', 'AQ', label='No', style='dashed')
dot.edge('AV', 'AH', label='Cleanup')
dot.edge('AH', 'AW', label='Import Error')

# Add styling
dot.attr(dpi='400', fontsize='12', labelloc='t', label='Scene Parser Flowchart\n(scene_parser.py)', labeljust='c')
dot.attr(bgcolor='lightgrey', rankdir='TB', splines='polyline')

# Render the flowchart
dot.render('/home/admin/Documents/GitHub/museum-system/docs/Structure/RPI/scene_parser_flowchart.png', view=False)