# 1. Štandardný MQTT listener (Pre tvoje ESP32 zariadenia a Python skripty)
listener 1883
protocol mqtt
allow_anonymous true

# 2. WebSockets listener (Pre tvoju Webovú appku/UI)
listener 9001
protocol websockets
allow_anonymous true